# version: '3.7'

services:
  postgres:
    image: postgis/postgis:12-3.3-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - network

  webserver:
    build:
      context: api/
    image: fastapi_service
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_database
      - DATABASE_URL=postgresql://user:password@postgres:5432/fastapi_database
      - DADATA_TOKEN=${DADATA_TOKEN?DADATA_TOKEN environment variable must be set}
    volumes:
      - type: volume
        source: logsvol
        target: /app/logs
      - type: bind
        source: ./api/backend # delete in prod and add copy
        target: /app/backend
      - type: bind
        source: ./cities_pbf
        target: /cities_pbf
    restart: always
    depends_on:
      - postgres
    ports:
      - "8901:8901"
    networks:
      - network

  frontend:
    build:
      context: front/
      dockerfile: Dockerfile
    image: react_service
    depends_on:
      - webserver
    ports:
      - "4200:80"
    networks:
      - network

volumes:
  pgdata:
  logsvol:


networks:
  network: